import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const coreSource=readFileSync(new URL('../app/assets/feed-core.js',import.meta.url),'utf8');
const dataSource=readFileSync(new URL('../app/assets/feed-data.js',import.meta.url),'utf8');
const uiSource=readFileSync(new URL('../app/assets/feed-ui.js',import.meta.url),'utf8');
const shellSource=readFileSync(new URL('../app/assets/shell.js',import.meta.url),'utf8');
const configSource=readFileSync(new URL('../app/assets/config.js',import.meta.url),'utf8');
const feedHtml=readFileSync(new URL('../app/feed.html',import.meta.url),'utf8');
const inboxHtml=readFileSync(new URL('../app/inbox.html',import.meta.url),'utf8');
const context={window:{},Date,Error,Object,Array,String,Number,Set};context.window.window=context.window;vm.runInNewContext(coreSource,context,{filename:'feed-core.js'});const core=context.window.SetfeedFeedCore;
const message=core.item({id:'msg_1',body:'Released content',deliverAt:'2026-08-01T12:00:00Z',releasedAt:'2026-08-01T12:00:01Z',status:'released',placement:'feed',origin:'inbound',source:'inbound',version:2,senderDisplayName:'Alex'});
assert.equal(message.body,'Released content');
assert.throws(()=>core.item({id:'msg_2',body:'early',deliverAt:'2026-08-02T12:00:00Z',status:'scheduled',placement:'feed',origin:'inbound',source:'inbound',version:1}),e=>e.code==='malformed_backend_response');
assert.ok(dataSource.includes('view:"feed",limit:"50"'));
assert.ok(dataSource.includes('body:{placement}'));
assert.ok(uiSource.includes('["Move to Inbox","inbox"]'));
assert.ok(uiSource.includes('["Hide","hidden"]'));
assert.ok(uiSource.includes('body.textContent=m.body'));
assert.ok(configSource.includes('feed: "./feed.html"'));
assert.ok(shellSource.includes('["feed","Feed"]'));
assert.ok(shellSource.includes('page==="feed"'));
assert.ok(feedHtml.includes('id="feed-list"'));
assert.ok(feedHtml.includes('id="feed-more"'));
assert.ok(inboxHtml.includes('href="./feed.html"'));
console.log('app feed behavior checks passed');
