import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../discord-oauth-complete.html', import.meta.url),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const script=scripts.at(-1);
class ClassList{constructor(){this.set=new Set(['hidden']);} add(c){this.set.add(c);} remove(c){this.set.delete(c);} contains(c){return this.set.has(c);} }
class El{constructor(id){this.id=id;this.textContent='';this.disabled=false;this.attrs={};this.classList=new ClassList();this.listeners={};} setAttribute(k,v){this.attrs[k]=String(v);} removeAttribute(k){delete this.attrs[k];} addEventListener(t,fn){this.listeners[t]=fn;} click(){return this.listeners.click?.({preventDefault(){}});} }
function deferred(){ let resolve,reject; const promise=new Promise((res,rej)=>{resolve=res;reject=rej;}); return {promise,resolve,reject}; }
async function run({hash='#discord_result='+'R'.repeat(32), state={ok:true,destination:'/inbox.html',intent:'continue'}, exchange, signIn, currentUser=null, start }={}){
  const ids=['title','message','restart','create-account','continue-discord']; const elements=Object.fromEntries(ids.map(id=>[id,new El(id)])); const calls=[]; const auth={currentUser, signOut(){calls.push(['signOut']);}, signInWithCustomToken: signIn || (async token=>{calls.push(['signIn',token]);})};
  const api={ DEFAULT_DESTINATION:'/inbox.html', parseResultFragment(h){calls.push(['parse',h]); if(!h) return {ok:false,code:'missing_result'}; if(h.includes('discord_error=')) return {ok:false,code:new URLSearchParams(h.slice(1)).get('discord_error')}; return {ok:true,resultCode:new URLSearchParams(h.slice(1)).get('discord_result')};}, validateStoredState(){calls.push(['validate']); return state;}, clearState(){calls.push(['clear']);}, exchangeDiscordResult: exchange || (async ({resultCode})=>{calls.push(['exchange',resultCode]); return {firebaseCustomToken:'token',destination:'/inbox.html',intent:'continue'};}), startDiscordSignIn: start || (async opts=>{calls.push(['start',opts]); return 'https://discord.com/oauth2/authorize?ok=1';}), mapError(code){ const map={discord_not_linked:['Discord account not linked','not linked'],discord_already_linked:['Use Continue with Discord','already'],active_session_changed:['Another Setfeed session is active','race'],firebase_custom_token_sign_in_failed:['Setfeed sign-in failed','failed'],malformed_intent:['Restart required','bad']}; const pair=map[code]||['Service unavailable','generic']; return {title:pair[0],message:pair[1],code:map[code]?code:'internal_error'}; }};
  const location={hash, pathname:'/discord-oauth-complete.html', search:'?ignored=1&discord_result=query', assigned:null, assign(v){calls.push(['assign',v]); this.assigned=v;}};
  const context={window:{sfAuth:auth,SetfeedDiscordAuth:api,location}, document:{getElementById:id=>elements[id]}, history:{replaceState(...args){calls.push(['replaceState', location.hash, ...args]); location.hash='';}}, URLSearchParams, console}; context.window.window=context.window;
  vm.runInNewContext(script, context, {filename:'discord-oauth-complete inline'});
  await new Promise(r=>setImmediate(r)); await new Promise(r=>setImmediate(r));
  return {elements,calls,location,auth};
}
let r=await run(); assert.ok(r.calls.findIndex(c=>c[0]==='replaceState') < r.calls.findIndex(c=>c[0]==='exchange'), 'fragment removed before exchange'); assert.equal(r.calls.find(c=>c[0]==='parse')[1].startsWith('#'), true, 'uses hash, not query');
r=await run({state:{ok:false,code:'malformed_intent'}}); assert.equal(r.calls.some(c=>c[0]==='exchange'), false); assert.equal(r.elements.restart.classList.contains('hidden'), false);
r=await run({state:{ok:true,destination:'/send.html#signin',intent:'continue'}, exchange:async()=>{throw {code:'discord_not_linked'};}}); assert.equal(r.calls.some(c=>c[0]==='start'), false); assert.equal(r.elements.restart.classList.contains('hidden'), false); assert.equal(r.elements['create-account'].classList.contains('hidden'), false); assert.equal(r.elements['continue-discord'].classList.contains('hidden'), true); assert.equal(r.elements.restart.textContent, 'Try Continue with Discord again'); await r.elements['create-account'].click(); { const opts=r.calls.filter(c=>c[0]==='start').at(-1)[1]; assert.equal(opts.auth, r.auth); assert.equal(opts.destination, '/send.html#signin'); assert.equal(opts.intent, 'create_account'); } assert.equal(JSON.stringify(r.calls).includes('R'.repeat(32)), true); assert.equal(JSON.stringify(r.calls.filter(c=>c[0]==='start')).includes('R'.repeat(32)), false);
r=await run({exchange:async()=>{throw {code:'discord_already_linked'};}}); assert.equal(r.elements['continue-discord'].classList.contains('hidden'), false); assert.equal(r.elements.restart.classList.contains('hidden'), true); await r.elements['continue-discord'].click(); assert.equal(r.calls.filter(c=>c[0]==='start').at(-1)[1].intent, 'continue');
r=await run({state:{ok:true,destination:'/inbox.html#hidden',intent:'create_account'}, exchange:async()=>{throw {code:'backend_unavailable'};}}); assert.equal(r.elements.restart.textContent,'Try account creation again'); await r.elements.restart.click(); let startCall=r.calls.filter(c=>c[0]==='start').at(-1)[1]; assert.equal(startCall.intent,'create_account'); assert.equal(startCall.destination,'/inbox.html#hidden');
r=await run({exchange:async()=>({firebaseCustomToken:'tok',destination:'/send.html',intent:'create_account'})}); assert.equal(r.elements.title.textContent,'Setfeed account created'); assert.deepEqual(r.calls.filter(c=>c[0]==='signIn'), [['signIn','tok']]); assert.ok(r.calls.findIndex(c=>c[0]==='clear') < r.calls.findIndex(c=>c[0]==='assign')); assert.equal(r.location.assigned,'/send.html');
r=await run({signIn:async()=>{throw new Error('no');}}); assert.equal(r.location.assigned,null); assert.equal(r.calls.some(c=>c[0]==='clear'), true);
r=await run({currentUser:{uid:'active'}, exchange:async()=>({firebaseCustomToken:'tok',destination:'/send.html',intent:'create_account'})}); assert.equal(r.calls.some(c=>c[0]==='signIn'), false); assert.equal(r.calls.some(c=>c[0]==='signOut'), false); assert.equal(r.location.assigned,null); assert.equal(r.elements.title.textContent,'Another Setfeed session is active');
const d=deferred(); r=await run({exchange:async()=>{throw {code:'discord_not_linked'};}, start:()=>d.promise}); const p=r.elements['create-account'].click(); assert.equal(r.elements['create-account'].disabled,true); assert.equal(r.elements['create-account'].attrs['aria-busy'],'true'); assert.equal(r.elements.restart.disabled,false); d.reject({code:'backend_unavailable'}); await p; assert.equal(r.elements['create-account'].disabled,false); assert.equal(r.elements['create-account'].attrs['aria-busy'],undefined); assert.equal(r.elements['create-account'].classList.contains('hidden'), true);
console.log('discord-oauth-complete behavior checks passed');
