import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
const source=readFileSync(new URL('../assets/encrypted-self.js', import.meta.url),'utf8');
function load(fetchImpl){ const ctx={crypto:webcrypto, TextEncoder, TextDecoder, setTimeout, clearTimeout, AbortController, btoa:s=>Buffer.from(s,'binary').toString('base64'), atob:s=>Buffer.from(s,'base64').toString('binary'), fetch:fetchImpl||(()=>{})}; ctx.globalThis=ctx; vm.runInNewContext(source,ctx); return ctx.SetfeedEncryptedSelf; }
const mod=load();
assert.equal(mod.FLAGS.uiVisible.encryptedSelfViewing,false);
assert.equal(mod.FLAGS.uiVisible.encryptedSelfComposition,false);
assert.equal(mod.FLAGS.uiVisible.releaseEmailSettings,false);
assert.deepEqual([...mod.compose.states], ['idle','key_loading','key_setup_required','recovery_required','draft_reserving','draft_reserved','encrypting','ready_to_finalize','finalizing','scheduled','failed_recoverable','failed_terminal','cancelled']);
assert.equal(mod.crypto.b64u(new Uint8Array([251,255,254])),'-__-');
assert.throws(()=>mod.crypto.b64uToBytes('-__='));
const aad=mod.crypto.textAad({accountKeyId:'ak',messageId:'m',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'});
assert.equal(Buffer.from(aad).toString(),'28:setfeed.website_self.text.v1|2:ak|1:m|1:d|24:2030-01-02T03:04:05.000Z');
const root1=await mod.crypto.importKw(webcrypto.getRandomValues(new Uint8Array(32)));
const root2=await mod.crypto.importKw(webcrypto.getRandomValues(new Uint8Array(32)));
const env=await mod.crypto.encryptText({rootKey:root1,plaintext:'hello 🔒',accountKeyId:'ak',messageId:'m',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'});
assert.equal(await mod.crypto.decryptText({rootKey:root1,envelope:env,accountKeyId:'ak',messageId:'m',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'}),'hello 🔒');
await assert.rejects(()=>mod.crypto.decryptText({rootKey:root2,envelope:env,accountKeyId:'ak',messageId:'m',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'}), e => e.code === 'decryption_authentication_failure');
await assert.rejects(()=>mod.crypto.decryptText({rootKey:root1,envelope:{...env,ciphertext:(env.ciphertext[0] === 'A' ? 'B' : 'A') + env.ciphertext.slice(1)},accountKeyId:'ak',messageId:'m',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'}), e => e.code === 'decryption_authentication_failure');
await assert.rejects(()=>mod.crypto.decryptText({rootKey:root1,envelope:env,accountKeyId:'ak',messageId:'m2',draftId:'d',releaseAt:'2030-01-02T03:04:05.000Z'}), e => e.code === 'decryption_authentication_failure');
assert.throws(()=>mod.crypto.validateEnvelope({...env, alg:'bad'}), e => e.code === 'malformed_backend_response');
assert.throws(()=>mod.crypto.validateEnvelope({...env, version:2}), e => e.code === 'malformed_backend_response');
let calls=[]; const auth={currentUser:{uid:'u1',isAnonymous:false, async getIdToken(force){calls.push(['token',force]); return force?'fresh':'old';}}};
const apiMod=load(async (url,init)=>{ calls.push(['fetch',url,init.headers.Authorization,init.cache,init.body]); if(calls.filter(c=>c[0]==='fetch').length===1) return {ok:false,status:401,json:async()=>({error:{code:'expired_token'}})}; return {ok:true,status:200,json:async()=>({ok:true})}; });
const api=new apiMod.ApiClient({auth,baseUrl:'https://api.test',timeoutMs:1000});
assert.deepEqual(await api.listMessages('upcoming'),{ok:true});
assert.equal(calls[1][2],'Bearer old'); assert.equal(calls[3][2],'Bearer fresh'); assert.equal(calls[1][3],'no-store');
const anon=new apiMod.ApiClient({auth:{currentUser:{uid:'a',isAnonymous:true,getIdToken(){throw Error('no')}}},baseUrl:'x'});
await assert.rejects(()=>anon.readAccountKey(), e => e.code === 'anonymous_account');
const op=mod.compose.newComposeOperation('uid','2030'); assert.equal(op.uid,'uid'); assert.ok(op.reserveIdempotencyKey!==op.finalizeIdempotencyKey);
assert.doesNotMatch(source,/console\.(log|warn|error|info|debug)/);
assert.doesNotMatch(source,/localStorage\.setItem\([^)]*(plaintext|rootKey|ciphertext|wrappedContentKey|firebase|token)/i);
console.log('encrypted-self foundation checks passed');
